CREATE EXTENSION IF NOT EXISTS postgis;

CREATE ROLE buyeoon_app
    LOGIN
    PASSWORD 'application-test-password'
    NOSUPERUSER;

GRANT CONNECT ON DATABASE buyeoon_test TO buyeoon_app;
GRANT USAGE, CREATE ON SCHEMA public TO buyeoon_app;

ALTER DEFAULT PRIVILEGES FOR ROLE CURRENT_USER IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO buyeoon_app;
ALTER DEFAULT PRIVILEGES FOR ROLE CURRENT_USER IN SCHEMA public
    GRANT USAGE ON SEQUENCES TO buyeoon_app;
