package com.buyeoon.location;

public enum LocationUsagePurpose {
	PLACE_DISTANCE, SAVED_PLACE_DISTANCE, MISSION_NEARBY, MISSION_DETAIL, MISSION_SUBMISSION, TRIP_START, CITIZEN_CARD_LOCATION_VERIFICATION, BUYEO_ENTRY_NOTIFICATION, BUYEO_EXIT_NOTIFICATION, SPECIAL_QUIZ_NEARBY_NOTIFICATION
}
